angular/src/app/app.module.ts, angular/src/app/layouts/base-layout/base-layout.component.html, angular/src/app/layouts/base-layout/base-layout.component.scss
- header -footer
-basic routing
refs:DW1-4
=> feat:Hoàn thành base layout

angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/components/blog-page/blog-page.component.html, angular/src/app/components/blog-page/blog-page.component.scss, angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.scss, angular/src/app/pages/product-detail-page/product-detail-page.component.spec.ts, angular/src/app/pages/product-detail-page/product-detail-page.component.ts
- product detail
- comment
- sản phẩm tương tự refs: DW1-5
=> feat:Hoàn thành product detail

angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/layouts/base-layout/base-layout.component.html, angular/src/app/pages/about-page/about-page.component.html, angular/src/app/pages/about-page/about-page.component.scss, angular/src/app/pages/about-page/about-page.component.spec.ts, angular/src/app/pages/about-page/about-page.component.ts, angular/src/app/pages/admin/dashboard/dashboard.component.html, angular/src/app/pages/blog-view-page/blog-view-page.component.html, angular/src/app/pages/blog-view-page/blog-view-page.component.scss, angular/src/app/pages/blog-view-page/blog-view-page.component.spec.ts, angular/src/app/pages/blog-view-page/blog-view-page.component.ts, angular/src/app/pages/contact-us-page/contact-us-page.component.html, angular/src/app/pages/contact-us-page/contact-us-page.component.scss, angular/src/app/pages/contact-us-page/contact-us-page.component.spec.ts, angular/src/app/pages/contact-us-page/contact-us-page.component.ts
- trang blog
- trang about
- trang contact
- trang dashboard refs: DW1-12
=> feat:Hoàn thành các trang phụ

API_Node/.gitignore, API_Node/package-lock.json, API_Node/package.json, API_Node/src/app.js, API_Node/src/controller/auth.js, API_Node/src/controller/category.js, API_Node/src/controller/product.js, API_Node/src/middlewares/checkPermission.js, API_Node/src/model/category.js, API_Node/src/model/product.js, API_Node/src/model/user.js, API_Node/src/routes/categories.js, API_Node/src/routes/products.js, API_Node/src/routes/users.js, API_Node/src/schemas/auth.js, API_Node/src/schemas/category.js, API_Node/src/schemas/product.js, API_Node/vite.config.js
- api product
- api category
- api user refs: DW1-13
=> feat: Hoàn thành api

angular/src/app/interface/category.ts, angular/src/app/interface/product.ts, angular/src/app/interface/user.ts, angular/src/app/pages/admin/category-list/category-list.component.html, angular/src/app/pages/admin/category-list/category-list.component.ts, angular/src/app/services/category/category.service.spec.ts, angular/src/app/services/category/category.service.ts, angular/src/app/services/product/product.service.spec.ts, angular/src/app/services/product/product.service.ts, angular/src/app/services/user/user.service.spec.ts, angular/src/app/services/user/user.service.ts
- product
- category
- user refs: DW1-14
=> feat: Hoàn thành service

angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/pages/admin/adminCategory/category-add/category-add.component.html, angular/src/app/pages/admin/adminCategory/category-add/category-add.component.ts
- Đã thêm được vào categories refs: DW1-22
=> feat: Hoàn Thành phần addCategories

API_Node/src/controller/category.js, API_Node/src/routes/categories.js, API_Node/src/schemas/category.js, angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/pages/admin/adminCategory/category-edit/category-edit.component.html, angular/src/app/pages/admin/adminCategory/category-edit/category-edit.component.spec.ts, angular/src/app/pages/admin/adminCategory/category-edit/category-edit.component.ts, angular/src/app/pages/admin/adminCategory/category-list/category-list.component.html
=> feat: Hoàn Thành Update

angular/src/app/pages/admin/adminProduct/product-list/product-list.component.html, angular/src/app/pages/admin/adminProduct/product-list/product-list.component.ts
-list sản phẩm
-xóa sản phẩm
refs:DW1-25
=> feat: xay dung list delete products

API_Node/src/controller/auth.js, API_Node/src/routes/users.js, API_Node/src/schemas/auth.js
=> feat: Hoàn Thành Api User

API_Node/src/controller/auth.js, API_Node/src/schemas/auth.js, angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/interface/user.ts, angular/src/app/layouts/admin-layout/admin-layout.component.html, angular/src/app/pages/admin/adminUser/user-list/user-list.component.html, angular/src/app/pages/admin/adminUser/user-list/user-list.component.spec.ts, angular/src/app/pages/admin/adminUser/user-list/user-list.component.ts, angular/src/app/pages/admin/adminUser/user-update/user-update.component.html, angular/src/app/pages/admin/adminUser/user-update/user-update.component.spec.ts, angular/src/app/pages/admin/adminUser/user-update/user-update.component.ts, angular/src/app/services/user/user.service.ts
- List User -Delete User
- Update User refs: DW1-31
=> feat: Hoàn Thành Xây dựng Users

angular/src/app/components/product-view/product-view.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.scss, angular/src/app/pages/product-detail-page/product-detail-page.component.ts
- product detail
- sản phẩm cùng loại refs: DW1-36
=> feat: Hoàn thành products detail

angular/src/app/components/categories/categories.component.html, angular/src/app/components/categories/categories.component.ts, angular/src/app/layouts/admin-layout/admin-layout.component.html, angular/src/app/layouts/admin-layout/admin-layout.component.scss, angular/src/app/layouts/admin-layout/admin-layout.component.ts
- Hiện danh mục ra ngoàii refs: DW1-35
=> feat: Hoàn Thành

angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/components/categories/categories.component.html, angular/src/app/pages/category-detail/category-detail.component.html, angular/src/app/pages/category-detail/category-detail.component.scss, angular/src/app/pages/category-detail/category-detail.component.spec.ts, angular/src/app/pages/category-detail/category-detail.component.ts
=> feat: Hoàn thành category detail

API_Node/src/app.js, API_Node/src/controller/blog.js, API_Node/src/controller/product.js, API_Node/src/model/blog.js, API_Node/src/routes/blogs.js, API_Node/src/schemas/blog.js
=> feat:xay-dung-api-blog

API_Node/src/model/blog.js, API_Node/src/schemas/blog.js, angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/interface/blog.ts, angular/src/app/layouts/admin-layout/admin-layout.component.html, angular/src/app/pages/admin/adminBlog/blog-add/blog-add.component.html, angular/src/app/pages/admin/adminBlog/blog-add/blog-add.component.spec.ts, angular/src/app/pages/admin/adminBlog/blog-add/blog-add.component.ts, angular/src/app/pages/admin/adminBlog/blog-edit/blog-edit.component.html, angular/src/app/pages/admin/adminBlog/blog-edit/blog-edit.component.spec.ts, angular/src/app/pages/admin/adminBlog/blog-edit/blog-edit.component.ts, angular/src/app/pages/admin/adminBlog/blog-list/blog-list.component.html, angular/src/app/pages/admin/adminBlog/blog-list/blog-list.component.spec.ts, angular/src/app/pages/admin/adminBlog/blog-list/blog-list.component.ts, angular/src/app/services/blog/blog.service.spec.ts, angular/src/app/services/blog/blog.service.ts
_ thêm , xỏa xóa blog
_ validate form
refs:DW1-39
=> feat: crud blog

API_Node/src/app.js, API_Node/src/controller/comment.js, API_Node/src/model/comment.js, API_Node/src/routes/comment.js, API_Node/src/schemas/comment.js, node_modules/.package-lock.json
- GetOne comment theo Id
- Get comment theo productId(không hiện được userId, giá trị = null)
- Create, Update, Delete comment thành công theo Id
-  refs: DW1-18
=> feat: Hoàn Thành api comment

angular/src/app/app.module.ts, angular/src/app/pages/admin/adminCategory/category-add/category-add.component.html, angular/src/app/pages/admin/adminCategory/category-add/category-add.component.ts, angular/src/app/pages/admin/adminCategory/category-edit/category-edit.component.html, angular/src/app/pages/admin/adminCategory/category-edit/category-edit.component.ts, angular/src/app/pages/admin/adminUser/user-update/user-update.component.html, angular/src/app/pages/admin/adminUser/user-update/user-update.component.ts
=> feat: Validate + confirm

angular/src/app/auth.guard.ts
- Fix lỗi khi không có user trên local thì về trang signin refs: DW1-44
=> hotfix: Fix private router

API_Node/src/routes/comment.js, angular/src/app/interface/comment.ts, angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.ts, angular/src/app/services/comment/comment.service.ts
=> feat: Hoàn thành add comment

angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.scss, angular/src/app/pages/product-detail-page/product-detail-page.component.ts
=> feat: hoàn thành delete comment

API_Node/src/app.js, API_Node/src/controller/cart.js, API_Node/src/model/cart.js, API_Node/src/routes/cart.js, API_Node/src/schemas/product.js
=> feat: hoàn thành api cart

angular/src/app/pages/cart/cart.component.html, angular/src/app/pages/cart/cart.component.ts
=> feat: Hoàn THành Xóa Cart

angular/src/app/layouts/base-layout/base-layout.component.html, angular/src/app/layouts/base-layout/base-layout.component.scss, angular/src/app/layouts/base-layout/base-layout.component.ts, angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.scss
=> feat: fix user,comment

API_Node/src/model/product.js, API_Node/src/model/user.js, API_Node/src/schemas/auth.js, API_Node/src/schemas/product.js, angular/src/app/components/product-view/product-view.component.html, angular/src/app/interface/product.ts, angular/src/app/layouts/admin-layout/admin-layout.component.html, angular/src/app/layouts/base-layout/base-layout.component.html, angular/src/app/layouts/base-layout/base-layout.component.scss, angular/src/app/layouts/base-layout/base-layout.component.ts, angular/src/app/pages/admin/adminProduct/product-add/product-add.component.html, angular/src/app/pages/admin/adminProduct/product-add/product-add.component.ts, angular/src/app/pages/admin/adminProduct/product-list/product-list.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.ts, angular/src/app/pages/sign/sign-up/sign-up.component.html, angular/src/app/pages/sign/sign-up/sign-up.component.ts, angular/src/app/services/upload/upload.service.ts
=> feat: upload image

API_Node/src/controller/upload.ts, API_Node/src/model/blog.js, API_Node/src/schemas/blog.js, angular/src/app/interface/blog.ts, angular/src/app/interface/user.ts, angular/src/app/pages/admin/adminBlog/blog-add/blog-add.component.html, angular/src/app/pages/admin/adminBlog/blog-add/blog-add.component.ts, angular/src/app/pages/admin/adminBlog/blog-edit/blog-edit.component.html, angular/src/app/pages/admin/adminBlog/blog-edit/blog-edit.component.scss, angular/src/app/pages/admin/adminBlog/blog-edit/blog-edit.component.ts, angular/src/app/pages/admin/adminBlog/blog-list/blog-list.component.html, angular/src/app/pages/admin/adminProduct/product-add/product-add.component.html, angular/src/app/pages/admin/adminProduct/product-update/product-update.component.html, angular/src/app/pages/admin/adminProduct/product-update/product-update.component.scss, angular/src/app/pages/admin/adminProduct/product-update/product-update.component.ts, angular/src/app/pages/admin/adminUser/user-list/user-list.component.html, angular/src/app/pages/admin/adminUser/user-update/user-update.component.html, angular/src/app/pages/admin/adminUser/user-update/user-update.component.scss, angular/src/app/pages/admin/adminUser/user-update/user-update.component.ts, angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/services/upload/upload.service.ts
=> feat: Hoàn thành update Image

angular/src/app/layouts/base-layout/base-layout.component.ts, angular/src/app/pages/sign/sign-in/sign-in.component.html, angular/src/app/pages/sign/sign-in/sign-in.component.ts, node_modules/.package-lock.json
=> feat: ban message error từ API

angular/src/app/components/blog-page/blog-page.component.html, angular/src/app/components/product-view/product-view.component.html, angular/src/app/pages/admin/adminBlog/blog-list/blog-list.component.html, angular/src/app/pages/admin/adminProduct/product-list/product-list.component.html, angular/src/app/pages/blog-view-page/blog-view-page.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.html
=> feat: fix hoàn thành

API_Node/src/controller/comment.js, API_Node/src/routes/comment.js, angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/components/blog-page/blog-page.component.html, angular/src/app/interface/comment.ts, angular/src/app/layouts/admin-layout/admin-layout.component.html, angular/src/app/layouts/base-layout/base-layout.component.html, angular/src/app/pages/admin/adminComment/list-comment/list-comment.component.html, angular/src/app/pages/admin/adminComment/list-comment/list-comment.component.scss, angular/src/app/pages/admin/adminComment/list-comment/list-comment.component.spec.ts, angular/src/app/pages/admin/adminComment/list-comment/list-comment.component.ts, angular/src/app/pages/admin/adminProduct/product-list/product-list.component.html, angular/src/app/pages/admin/adminUser/user-update/user-update.component.html, angular/src/app/pages/category-detail/category-detail.component.html, angular/src/app/pages/product-detail-page/product-detail-page.component.html, angular/src/app/services/comment/comment.service.ts, node_modules/.package-lock.json
=> feat: Hoàn Thành list comment

angular/src/app/pages/admin/adminComment/list-comment/list-comment.component.html, angular/src/app/pages/admin/adminComment/list-comment/list-comment.component.ts
=> feat: Hoành Thành delete admin comment

angular/src/app/components/blog-page/blog-page.component.html, angular/src/app/components/product-view/product-view.component.html, angular/src/app/pages/admin/adminBlog/blog-list/blog-list.component.html, angular/src/app/pages/admin/adminProduct/product-list/product-list.component.html
=> fix: fix thành công

angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/auth.interceptor.spec.ts, angular/src/app/auth.interceptor.ts, angular/src/app/components/product-view/product-view.component.html, angular/src/app/pages/category-detail/category-detail.component.html, angular/src/app/services/blog/blog.service.ts, angular/src/app/services/category/category.service.ts, angular/src/app/services/product/product.service.ts
=> feat: Hoàn thành intercept

API_Node/src/app.js, API_Node/src/controller/bill.js, API_Node/src/model/bill.js, API_Node/src/routes/bill.js, API_Node/src/schemas/bill.js
=> feat: api checkout and bill

angular/src/app/pages/pay/pay.component.html
- có thể thay đổi địa chỉ refs: DW1-71
=> fix: fix xong pay

angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/interface/bill.ts, angular/src/app/layouts/admin-layout/admin-layout.component.html, angular/src/app/pages/admin/adminBill/detail-bill/detail-bill.component.html, angular/src/app/pages/admin/adminBill/detail-bill/detail-bill.component.scss, angular/src/app/pages/admin/adminBill/detail-bill/detail-bill.component.spec.ts, angular/src/app/pages/admin/adminBill/detail-bill/detail-bill.component.ts, angular/src/app/pages/admin/adminBill/list-bill/list-bill.component.html, angular/src/app/pages/admin/adminBill/list-bill/list-bill.component.spec.ts, angular/src/app/pages/admin/adminBill/list-bill/list-bill.component.ts
=> feat: Hoàn Thành admin bill

API_Node/src/app.js, API_Node/src/controller/status.js, API_Node/src/model/status.js, API_Node/src/routes/status.js, API_Node/src/schemas/status.js
=> feat: api status

API_Node/src/model/bill.js, API_Node/src/model/product.js, API_Node/src/model/status.js, angular/src/app/app-routing.module.ts, angular/src/app/app.module.ts, angular/src/app/interface/product.ts, angular/src/app/pages/bill/bill.component.html, angular/src/app/pages/bill/bill.component.spec.ts, angular/src/app/pages/bill/bill.component.ts
=> feat: detail-cart

API_Node/src/controller/bill.js, API_Node/src/model/bill.js, angular/src/app/interface/bill.ts, angular/src/app/interface/status.ts, angular/src/app/pages/admin/adminBill/detail-bill/detail-bill.component.html, angular/src/app/pages/admin/adminBill/detail-bill/detail-bill.component.ts, angular/src/app/pages/admin/adminBill/list-bill/list-bill.component.html, angular/src/app/pages/admin/adminBill/list-bill/list-bill.component.ts, angular/src/app/pages/bill/bill.component.html, angular/src/app/pages/bill/bill.component.scss, angular/src/app/services/bill/bill.service.ts, angular/src/app/services/status/status.service.spec.ts, angular/src/app/services/status/status.service.ts
=> Fix detail cart

API_Node/src/app.js, API_Node/src/model/bill.js, API_Node/src/model/cancelOrder.js, API_Node/src/routes/cancelOrder.js, angular/src/app/pages/bill/bill.component.html, angular/src/app/pages/bill/bill.component.ts
=> feat: Hủy đơn hàng
